### ISSUE TITLE
Update to useable with ZF2.4?

### ISSUE THREAD

**Issue by Dexus** [heiglandreas/HybridAuth#25]
See topic!

**Comment by heiglandreas** [comment]
Hey @Dexus . Thanks for raising the issue. But would you mind being a bit more specific as to what **your** actual issue is? Does it not install? Does it not work?  I'd be eager to help but right at the moment I don't know really **how** 😦

**Comment by Dexus** [comment]
I can't install it.

```
composer require org_heigl/hybridauth
Using version ^1.0 for org_heigl/hybridauth
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - org_heigl/hybridauth v1.0.0 requires zendframework/zendframework >=2.1,<2.3.x-dev -> satisfiable by zendframework/zendframework[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.1, 2.2.10, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9] but these conflict with your requirements or minimum-stability.
    - org_heigl/hybridauth 1.0.1 requires hybridauth/hybridauth ~3.0 -> satisfiable by hybridauth/hybridauth[3.0.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for org_heigl/hybridauth ^1.0 -> satisfiable by org_heigl/hybridauth[1.0.1, v1.0.0].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by heiglandreas** [comment]
The issue here is that the current stable release (which is 1.0.1) depends on the dev-branch 3.0.0 of hybridauth itself. and **that** one is marked as dev but you specified in your ```composer.json``` to require only stable packages. According to [Igors approach](https://igor.io/2013/02/07/composer-stability-flags.html) you can circumvent that by adding the following to the ```require```-section of your ```composer.json```:

```
   "require" : {
       "hybridauth/hybridauth" : "@dev"
    }
```

That way composer knows that a dev-version of hybridauth is OK and it should resolve the dependency even though you only want stable libs.

I hope that solves the issue! 

BTW: you might want to use ```composer require org_heigl/hybridauth:dev-feature/multipleProviders``` as that branch allows to use multiple providers instead of only one.

There might be a better way to do that but I'll have to check that! I'll keep you updated via this issue!

**Comment by heiglandreas** [comment]
I've just updated the installation-instructions in the [README](https://github.com/heiglandreas/HybridAuth/blob/8ef5ee333e917cfe460f65d131cf25d7c183da7a/README.md)

**Comment by heiglandreas** [comment]
I've just tagged the version 2.0.0 - but it still has the issue with needing to call 2 composer-commands:

```
    composer require --no-update hybridauth/hybridauth:@dev
    composer require org_heigl/hybridauth
```

**Comment by Dexus** [comment]
yeah, looks so. Thank you.
